apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.elk.elasticsearch.name }}
  namespace: {{ .Values.elk.namespace }}
spec:
  selector:
    app: {{ .Values.elk.elasticsearch.name }}
  ports:
    - protocol: {{ .Values.elk.elasticsearch.protocol }}
      port: {{ .Values.elk.elasticsearch.port }}
      targetPort: {{ .Values.elk.elasticsearch.targetPort }}
  type: {{ .Values.elk.elasticsearch.type }}
