apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.elk.filebeat.name }}
  namespace: {{ .Values.elk.namespace }}
  labels:
    app: {{ .Values.elk.filebeat.name }}
spec:
  replicas: {{ .Values.elk.filebeat.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.elk.filebeat.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.elk.filebeat.name }}
    spec:
      containers:
      - name: {{ .Values.elk.filebeat.name }}
        image: {{ .Values.elk.filebeat.image }}
        args: [
          "-e", 
          "-c", "/usr/share/filebeat/filebeat.yml"
        ]
        securityContext:
          runAsUser: 0 
        volumeMounts:
        - name: config
          mountPath: /usr/share/filebeat/filebeat.yml
          subPath: filebeat.yml
        - name: log-volume
          mountPath: /var/log/pods
      volumes:
      - name: config
        configMap:
          name: filebeat-config
      - name: log-volume
        hostPath:
          path: /var/log/pods
          type: DirectoryOrCreate
