apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.elk.kibana.name }}
  namespace: {{ .Values.elk.namespace }}
spec:
  replicas: {{ .Values.elk.kibana.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.elk.kibana.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.elk.kibana.name }}
    spec:
      containers:
      - name: {{ .Values.elk.kibana.name }}
        image: {{ .Values.elk.kibana.image }}
        ports:
        - containerPort: {{ .Values.elk.kibana.containerPort }}
        env:
        - name: ELASTICSEARCH_HOSTS
          value: "http://{{ .Values.elk.elasticsearch.name }}:9200"
        - name: ELASTICSEARCH_USERNAME
          value: "{{ .Values.elk.kibana.auth.username }}"
        - name: ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.elk.kibana.auth.existingSecret }}"
              key: elastic-password