apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.elk.logstash.name }}
  namespace: {{ .Values.elk.namespace }}
spec:
  replicas: {{ .Values.elk.logstash.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.elk.logstash.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.elk.logstash.name }}
    spec:
      containers:
      - name: {{ .Values.elk.logstash.name }}
        image: docker.elastic.co/logstash/logstash:7.10.0
        ports:
        - containerPort: {{ .Values.elk.logstash.containerPort }}
        volumeMounts:
        - name: logstash-config
          mountPath: /usr/share/logstash/pipeline
      volumes:
      - name: logstash-config
        configMap:
          name: logstash-config
