apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: {{ .Values.elk.namespace }}
data:
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }

    filter {
      if [app] == "taytelar-backend" {
        mutate { add_field => { "[@metadata][index]" => "taytelar-backend-logs" } }
      }
      else if [app] == "marketing-backend" {
        mutate { add_field => { "[@metadata][index]" => "marketing-backend-logs" } }
      }
      else if [app] == "bus-backend" {
        mutate { add_field => { "[@metadata][index]" => "bus-backend-logs" } }
      }
    }

    output {
      elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        user => "elastic"
        password => "${ELASTIC_PASSWORD}"
        index => "%{[@metadata][index]}-%{+YYYY.MM.dd}"
      }
    }