apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.elk.logstash.name }}
  namespace: {{ .Values.elk.namespace }}
spec:
  selector:
    app: {{ .Values.elk.logstash.name }}
  ports:
    - protocol: {{ .Values.elk.logstash.protocol }}
      port: {{ .Values.elk.logstash.port }}
      targetPort: {{ .Values.elk.logstash.targetPort }}
