replicaCount: 1

frontend:
  name: frontend
  image:
    repository: 794038231860.dkr.ecr.ap-south-1.amazonaws.com/taytelar-frontend
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    name: frontend
    port: 80
    targetPort: 3000

backend:
  name: backend
  image:         
    repository: 794038231860.dkr.ecr.ap-south-1.amazonaws.com/taytelar-backend
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    name: backend
    port: 8081
    targetPort: 8081
  spring:
    profile: dev

env:
  app: 
    spring: test
  mail:
    to:
      username: test
  aws:
    region: ap-south-1
    access_key: test
    secret_key: test
    bucketName: test
    reviewbucket: test
    marketingbucket: test
    nandhubus_bucket: test
  email:
    template: test

thirdparty:
  toll:
    key: test
  razorpay_api:
    id: test
    secret: test
    x_account_number: test
  fastsms_api:
    id: test
    url: test
  google_maps_api:
    key: test
    url: test
  mail:
    address: test
    user: test
    password: test
  falcon:
    key: test
    url: test
    domain: test
  brevo:
    key: test

fuel:
  price:
    multiplier: test

distance:
  calculation:
    factor: test
    defaultKm: test

gst:
  ac:
    percentage: test
  non:
    ac:
      percentage: test

whatsapp:
  phoneid: test
  token: test
  webhooktoken: test

  #marketing
imap:
  host: test
  port: 993
  username: test
  password: test
   
smtp:
  host: test
  port: 587
  username: test
  password: test

database:
  postgres:
    name: postgres-service
    image: postgres:13
    username: test
    password: test
    dbname: Tay-Telar
    marketing:
      dbname: dm-email 
    bus:
      dbname: bus_reservation_db
    port: 5432
    enabled: true
    storage:
      size: 1Gi

  mongodb:
    name: mongo-service
    image: mongo:latest
    dbname: TayTelar
    enabled: true
    port: 27017

  redis:
    host: redis-service
    port: 6379
    password: test

hpa:
  enabled: true
  name: backend-hpa
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
ingress:
  enabled: true
  name: taytelar-ingress
  host: dev.taytelar.com
busybox:
  replicaCount: 1
  image:
    repository: busybox
  volumeMount:
    path: /var/log/pods
  volume:
    type: DirectoryOrCreate
cipher:
  secret:
    key: test
application:
  security:
    jwt:
      secret:
        key: test
    token:
      secret:
        key: test  
logo:
  image:
    url: test

marketing:
  backend:
    name: marketing-backend
  image:         
    repository: 794038231860.dkr.ecr.ap-south-1.amazonaws.com/marketing-backend-service
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    name: marketing-backend
    port: 8084
    targetPort: 8084
  ingress:
    enabled: true
    name: marketing-ingress
    host: marketing.seabed2crest.com
  
campaign:
  frontend:
    name: marketing-frontend
    image:
      repository: 794038231860.dkr.ecr.ap-south-1.amazonaws.com/marketing-frontend-service
      tag: latest
      pullPolicy: Always
    service:
      type: ClusterIP
      name: marketing-frontend
      port: 80
      targetPort: 80

bus:
  backend:
    name: bus-backend
  image:         
    repository: 794038231860.dkr.ecr.ap-south-1.amazonaws.com/bus-backend-service
    tag: latest
    pullPolicy: Always
    url: test
    amenities:
      url: test
  service:
    type: ClusterIP
    name: bus-backend
    port: 8086
    targetPort: 8086
  ingress:
    enabled: true
    name: bus-ingress
    host: dev.nandubus.in
  
  postgres:
    name: bus-postgres-service
    image: postgres:13
    dbname: bus_reservation_db
    port: 5433
    enabled: true
    storage:
      size: 1Gi
  

nandhubus:
  frontend:
    name: bus-frontend
    image:
      repository: 794038231860.dkr.ecr.ap-south-1.amazonaws.com/bus-frontend-service
      tag: latest
      pullPolicy: Always
    service:
      type: ClusterIP
      name: bus-frontend
      port: 80
      targetPort: 3000

initialUser: test