replicaCount: 1

frontend:
  name: frontend
  image:
    repository: 794038231860.dkr.ecr.ap-south-1.amazonaws.com/taytelar-frontend:latest
    # tag: latest
  service:
    type: ClusterIP
    name: frontend-service
    port: 80
    targetPort: 80

backend:
  name: backend
  image:
    repository: 794038231860.dkr.ecr.ap-south-1.amazonaws.com/taytelar-backend
    tag: latest
  service:
    type: ClusterIP
    name: backend-service
    port: 8081
    targetPort: 8081
  spring:
    profile: dev
  pullPolicy: IfNotPresent

env:
  aws:
    region: ap-south-1
    access_key: test
    secret_key: test
    bucketName: test

thirdparty:
  razopay_api:
    id: test
    secret: test
  fastsms_api:
    id: test
    url: test
  google_maps_api:
    key: test
    url: test

hpa:
  enabled: true
  name: backend-hpa
  minReplicas: 1
  maxReplicas: 20
  targetCPUUtilizationPercentage: 80

ingress:
  enabled: true
  name: taytelar-ingress
  host: dev.taytelar.com

busybox:
  replicaCount: 1
  image:
    repository: busybox
  volumeMount:
    path: /var/log/pods
  volume:
    type: DirectoryOrCreate

