database:
  namespace: database
  postgres:
    name: postgres-service
    image: postgres:13
    username: postgres
    password: taytelar
    dbname: Tay-Telar
    port: 5432
    enabled: true
    storage:
      size: 1Gi

  mongodb:
    name: mongo-service
    image: mongo:latest
    dbname: TayTelar
    enabled: true
    port: 27017