efk: 
  namespace: taytelar-ns

  elasticsearch:
    image: "quay.io/fluentd_elasticsearch/elasticsearch:v7.3.2"
    replicas: 2
    servicePort: 9200
  
  fluentd:
    image: "quay.io/fluentd_elasticsearch/fluentd:v2.7.0"
    resources:
      limits:
        memory: "500Mi"
      requests:
        cpu: "100m"
        memory: "200Mi"
  
  kibana:
    image: "docker.elastic.co/kibana/kibana-oss:7.3.2"
    replicas: 1
    servicePort: 5601
