monitoring:
  namespace: monitoring

  grafana:
    image: "grafana/grafana:latest"
    name: grafana
    replicas: 1
    service:
      port: 3000
      targetPort: 3000
      type: ClusterIP
    datasources:
      datasource.yaml:
        apiVersion: 1
        datasources:
          - name: Prometheus
            type: prometheus
            access: proxy
           # url: http://{{ .Values.monitoring.prometheus.name }}.{{ .Values.monitoring.namespace }}.svc.cluster.local:{{ .Values.monitoring.prometheus.service.port }}
            url: http://prometheus-service:9090
            isDefault: true

  prometheus:
    image: "prom/prometheus:latest"
    name: prometheus
    replicas: 1
    service:
      port: 9090
      targetPort: 9090
      type: ClusterIP
    configMapName: prometheus-config

  prometheusConfigMap:
    name: prometheus-config

  ingress:
    enabled: true
    name: monitoring-ingress
    grafana:
      host: grafana.taytelar.com
    prometheus:
      host: prometheus.taytelar.com
backend:
  namespace: taytelar-ns