monitoring:
  namespace: monitoring

  grafana:
    image: "grafana/grafana:latest"
    name: grafana
    replicas: 1
    service:
      port: 3000
      targetPort: 3000
      type: ClusterIP

  prometheus:
    image: "prom/prometheus:latest"
    name: prometheus
    replicas: 1
    service:
      port: 9090
      targetPort: 9090
      type: ClusterIP
    configMapName: prometheus-config

  prometheusConfigMap:
    name: prometheus-config

  ingress:
    enabled: true
    name: monitoring-ingress
    grafana:
      host: grafana.taytelar.com
    prometheus:
      host: prometheus.taytelar.com