apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: ecr-secret

      containers:
        - name: backend
          image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.backend.service.port }}

          # Define environment variables here
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.backend.spring.profile }}
              
            # PostgreSQL values
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://{{ .Values.database.postgres.name }}:5432/{{ .Values.database.postgres.dbname }}
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: postgres-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: postgres-password

            # MongoDB values
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://{{ .Values.database.mongodb.name }}:27017/{{ .Values.database.mongodb.dbname }}

            # Razorpay Credentials
            - name: RAZORPAY_API_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: razorpay-api-key-id
            - name: RAZORPAY_API_KEY_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: razorpay-api-key-secret

            # Fast2SMS Credentials
            - name: FAST2SMS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: fast2sms-api-id
            - name: FAST2SMS_SMS_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: fast2sms-api-url

            # AWS credentials and bucket
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: aws-access-key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: aws-secret-key
            - name: AWS_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: aws-bucket-name

            - name: GOOGLE_MAP_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: google-map-api-key

            - name: GOOGLE_MAP_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: google-map-api-url
            - name: AWS_REGION
              value: ap-south-1

          # Define volume mounts here
          volumeMounts: 
            - mountPath: /var/log/pods
              name: log-volume

          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"

      volumes:
        - name: log-volume
          hostPath:
            path: /var/log/pods/  
            type: DirectoryOrCreate
