apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.backend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.name }}
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: {{ .Values.backend.name }}
          image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
          imagePullPolicy: {{ .Values.backend.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.service.port }}
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://{{ .Values.database.postgres.name }}:{{ .Values.database.postgres.port }}/{{ .Values.database.postgres.dbname }}
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: postgres-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: postgres-password
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://{{ .Values.database.mongodb.name }}:{{ .Values.database.mongodb.port }}/{{ .Values.database.mongodb.dbname }}
            - name: RAZORPAY_API_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: razorpay-api-key-id
            - name: RAZORPAY_API_KEY_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: razorpay-api-key-secret
            - name: FAST2SMS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: fast2sms-api-id
            - name: FAST2SMS_SMS_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: fast2sms-api-url
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: aws-access-key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: aws-secret-key
            - name: AWS_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: aws-bucket-name
            - name: GOOGLE_MAP_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: google-map-api-key
            - name: GOOGLE_MAP_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: google-map-api-url
            - name: AWS_REGION
              value: {{ .Values.env.aws.region }}
            - name: CIPHER_SECRET_KEY
              value: {{ .Values.cipher.secret.key }}
            - name: JWT_SECRET_KEY
              value: {{ .Values.application.security.jwt.secret-key }}
            - name: JWT_EXPIRATION
              value: {{ .Values.application.security.jwt.expiration }}
          volumeMounts: 
            - mountPath: /var/log/pods
              name: log-volume
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: log-volume
          hostPath:
            path: /var/log/pods/  
            type: DirectoryOrCreate
