apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.bus.postgres.name }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-name: "bus-postgres-service"
    
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: {{ .Values.bus.postgres.port }}
      targetPort: 5432
  selector:
    app: bus-postgres
