apiVersion: apps/v1
kind: Deployment
metadata:
  name: bus-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bus-postgres
  template:
    metadata:
      labels:
        app: bus-postgres
    spec:
      containers:
      - name: "{{ .Values.bus.postgres.name }}"
        image: "{{ .Values.bus.postgres.image }}"
        env: 
        - name: PGDATA
          value: "{{ .Values.bus.postgres.datapath}}"
        - name: POSTGRES_DB
          value: "{{ .Values.bus.postgres.dbname }}"
        - name: POSTGRES_USER
          value: "{{ .Values.database.postgres.username }}"
        - name: POSTGRES_PASSWORD
          value: "{{ .Values.database.postgres.password }}"
        - name: PGOPTIONS
          value: "-c idle_in_transaction_session_timeout=600000"
        ports:
        - containerPort: 5433
        lifecycle:
          preStop:
            exec:
              command: [ "sh", "-c", "psql -U $POSTGRES_USER -d $POSTGRES_DB -c \"SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE state = 'idle' AND now() - query_start > interval '10 minutes';\"" ]
#        volumeMounts:
#          - name: postgres-storage
#            mountPath: "{{ .Values.bus.postgres.datapath}}"
#      volumes:
#        - name: postgres-storage
#          persistentVolumeClaim:
#            claimName: postgres-pvc