apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.bus.backend.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: {{ .Values.bus.backend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.bus.backend.name }}
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: {{ .Values.bus.backend.name }}
          image: {{ .Values.bus.image.repository }}:{{ .Values.bus.image.tag }}
          imagePullPolicy: {{ .Values.bus.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.bus.service.port }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://{{ .Values.bus.postgres.name }}:{{ .Values.bus.postgres.port }}/{{ .Values.bus.postgres.dbname }}"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: postgres-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: postgres-password
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: aws-access-key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: aws-secret-key
            - name: AWS_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: nandhubus-bucket
            - name: AWS_REGION
              value: "{{ .Values.env.aws.region }}"
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: jwt-secret-key
            - name: JWT_EXPIRATION
              value: "3600000"
            - name: REFRESH_TOKEN_EXPIRATION
              value: "86400000"
            - name: SMTP_HOST
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: smtp-host
            - name: SMTP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: smtp-username
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: smtp-password
            - name: IMAP_HOST
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: imap-host
            - name: IMAP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: imap-username
            - name: IMAP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: imap-password
            - name: GOOGLE_MAPS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: google-map-api-key
            - name: GOOGLE_MAPS_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: google-map-api-url
            - name: RAZORPAY_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: razorpay-api-key-id
            - name: RAZORPAY_KEY_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: razorpay-api-key-secret
            - name: FAST2SMS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: fast2sms-api-id
            - name: FAST2SMS_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: fast2sms-api-url
            - name: BUS_IMAGE_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: bus-image-url
            - name: EMAIL_TEMPLATE
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: email-template
            - name: CIPHER_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: cipher-secret-key
            - name: AMENITIES_IMAGE_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: amenities-image-url
            - name: TOLL_API_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: toll-api-key
            - name: FUEL_PRICE_MULTIPLIER
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: fuel-price
            - name: DISTANCE_CALCULATION_FACTOR
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: distance-calculation-factor
            - name: DISTANCE_CALCULATION_DEFAULT_KM
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: distance-calculation-default-km
            - name: GST_AC_PERCENTAGE
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: gst-ac-percentage
            - name: GST_NON_AC_PERCENTAGE
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: gst-non-ac-percentage
            - name: PLATFORM_FEES
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: platform-fees
            - name: PLATFORM_GST
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: platform-gst