apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: backend-external-secrets
  namespace: taytelar-ns
spec:
  backendType: secretsManager
  data:
    - key: taytelar-all-secrets
      name: postgres-username
      property: postgres-credentials.username
    - key: taytelar-all-secrets
      name: postgres-password
      property: postgres-credentials.password
    - key: taytelar-all-secrets
      name: razorpay-api-key-id
      property: razorpay-credentials.api.key.id
    - key: taytelar-all-secrets
      name: razorpay-api-key-secret
      property: razorpay-credentials.api.key.secret
    - key: taytelar-all-secrets
      name: fast2sms-api-id
      property: fast2sms-api.api.key
    - key: taytelar-all-secrets
      name: fast2sms-api-url
      property: fast2sms-api.api.url
    - key: taytelar-all-secrets
      name: aws-access-key
      property: aws-credentials.aws.access.key.id
    - key: taytelar-all-secrets
      name: aws-secret-key
      property: aws-credentials.aws.secret.key
    - key: taytelar-all-secrets
      name: aws-bucket-name
      property: aws-bucket
    - key: taytelar-all-secrets
      name: google-map-api-key
      property: google-map-api.api.key
    - key: taytelar-all-secrets
      name: google-map-api-url
      property: google-map-api.api.url
