apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: taytelar-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
        - name: external-dns
          image: k8s.gcr.io/external-dns/external-dns:latest
          args:
            - --source=ingress
            - --domain-filter=taytelar.com
            - --provider=aws
            - --policy=upsert-only
            - --registry=txt
            - --txt-owner-id=external-dns
            - --log-level=info
          env:
            - name: AWS_REGION
              value: ap-south-1
