apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  # annotations:
    # service.beta.kubernetes.io/aws-load-balancer-arn: arn:aws:elasticloadbalancing:ap-south-1:794038231860:loadbalancer/app/taytelar-front-end/dbc19430eb2d8777
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
  - protocol: TCP
    port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.service.targetPort }}
  selector:
    app: frontend
