apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.campaign.service.name }}
spec:
  type: {{ .Values.campaign.service.type }}
  ports:
  - protocol: TCP
    port: {{ .Values.campaign.service.port }}
    targetPort: {{ .Values.campaign.service.targetPort }}
  selector:
    app: {{ .Values.campaign.frontend.name }}
