apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.marketing.service.name }}
spec:
  type: {{ .Values.marketing.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.marketing.service.port }}
      targetPort: {{ .Values.marketing.service.targetPort }}
  selector:
    app: {{ .Values.marketing.backend.name }}
