apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.mongodb.name }}
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017  # Ensure this matches the containerPort in the Deployment
  selector:
    app: {{ .Release.Name }}-mongo
  type: ClusterIP
