apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: {{ .Values.database.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: "{{ .Values.database.mongodb.name }}"
        image: "{{ .Values.database.mongodb.image }}"
        ports:
        - containerPort: 27017
