apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-database-namespace-access
  namespace: taytelar-ns
spec:
  podSelector: {}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: database
