apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller
  labels:
    app.kubernetes.io/name: taytelar-ingress
    app.kubernetes.io/instance: taytelar-ingress
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
      nodePort: 30080
  selector:
    app.kubernetes.io/name: taytelar-ingress
