apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller
  labels:
    app.kubernetes.io/name: taytelar-ingress
    app.kubernetes.io/instance: taytelar-ingress
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app.kubernetes.io/name: taytelar-ingress
