apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  storageClassName: {{ .Values.database.postgres.storageclass }}
  accessModes:
    - {{ .Values.database.postgres.accessmode }}
  resources:
    requests:
      storage: {{ .Values.database.postgres.storagesize }}