apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.postgres.name }}
spec:
  ports:
  - protocol: TCP
    port: {{ .Values.database.postgres.port }}
    targetPort: 5432
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-postgres
