apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.postgres.name }}
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ .Values.database.postgres.port }}
      targetPort: 5432
  selector:
    app: postgres
