apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-postgres
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-postgres
    spec:
      containers:
      - name: "{{ .Values.database.postgres.name }}"
        image: "{{ .Values.database.postgres.image }}"
        env:
        - name: POSTGRES_DB
          value: "{{ .Values.database.postgres.dbname }}"
        - name: POSTGRES_USER
          value: "{{ .Values.database.postgres.username }}"
        - name: POSTGRES_PASSWORD
          value: "{{ .Values.database.postgres.password }}"
        ports:
        - containerPort: 5432
