apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: taytelar-ns
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: {{ .Values.database.redis.port | default 6379 }}
      targetPort: 6379
  type: ClusterIP
