apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  amenities-image-url: {{ .Values.bus.image.amenities.url | b64enc }}
  aws-access-key: {{ .Values.env.aws.access_key | b64enc }}
  aws-bucket-name: {{ .Values.env.aws.bucketName | b64enc }}
  aws-marketing-bucket: {{ .Values.env.aws.marketingbucket | b64enc }}
  aws-review-bucket: {{ .Values.env.aws.reviewbucket | b64enc }}
  aws-secret-key: {{ .Values.env.aws.secret_key | b64enc }}
  brevo_key: {{ .Values.thirdparty.brevo.key | b64enc }}
  bus-image-url: {{ .Values.bus.image.url | b64enc }}
  cipher-secret-key: {{ .Values.cipher.secret.key | b64enc }}
  database-bus-dbname: {{ .Values.database.postgres.bus.dbname | b64enc }}
  database-marketing-dbname: {{ .Values.database.postgres.marketing.dbname | b64enc }}
  database-mongodb-dbname: {{ .Values.database.mongodb.dbname | b64enc }}
  database-postgres-dbname: {{ .Values.database.postgres.dbname | b64enc }}
  distance-calculation-default-km: {{ .Values.distance.calculation.defaultKm | toString | b64enc }}
  distance-calculation-factor: {{ .Values.distance.calculation.factor | toString | b64enc }}
  email-template: {{ .Values.env.email.template | b64enc }}
  env-app-spring: {{ .Values.env.app.spring | b64enc }}
  env-mail-to-username: {{ .Values.env.mail.to.username | b64enc }}
  falcon-domain: {{ .Values.thirdparty.falcon.domain | b64enc }}
  falcon-key: {{ .Values.thirdparty.falcon.key | b64enc }}
  falcon-url: {{ .Values.thirdparty.falcon.url | b64enc }}
  fast2sms-api-id: {{ .Values.thirdparty.fastsms_api.id | b64enc }}
  fast2sms-api-url: {{ .Values.thirdparty.fastsms_api.url | b64enc }}
  fuel-price: {{ .Values.fuel.price.multiplier | toString | b64enc }}
  google-map-api-key: {{ .Values.thirdparty.google_maps_api.key | b64enc }}
  google-map-api-url: {{ .Values.thirdparty.google_maps_api.url | b64enc }}
  gst-ac-percentage: {{ .Values.gst.ac.percentage | toString | b64enc }}
  gst-non-ac-percentage: {{ .Values.gst.non.ac.percentage | toString | b64enc }}
  imap-host: {{ .Values.imap.host | b64enc }}
  imap-password: {{ .Values.imap.password | b64enc }}
  imap-port: {{ .Values.imap.port | toString | b64enc }}
  imap-username: {{ .Values.imap.username | b64enc }}
  jwt-secret-key: {{ .Values.application.security.jwt.secret.key | b64enc }}
  jwt-token-secret-key: {{ .Values.application.security.token.secret.key | b64enc }}
  mail-address: {{ .Values.thirdparty.mail.address | b64enc }}
  mail-password: {{ .Values.thirdparty.mail.password | b64enc }}
  mail-user: {{ .Values.thirdparty.mail.user | b64enc }}
  nandhubus-bucket: {{ .Values.env.aws.nandhubus_bucket | b64enc }}
  postgres-password: {{ .Values.database.postgres.password | b64enc }}
  postgres-username: {{ .Values.database.postgres.username | b64enc }}
  razorpay-api-key-id: {{ .Values.thirdparty.razorpay_api.id | b64enc }}
  razorpay-api-key-secret: {{ .Values.thirdparty.razorpay_api.secret | b64enc }}
  razorpay-x-account-number: {{ .Values.thirdparty.razorpay_api.x_account_number | toString | b64enc }}
  redis-password: {{ .Values.database.redis.password | b64enc }}
  smtp-host: {{ .Values.smtp.host | b64enc }}
  smtp-password: {{ .Values.smtp.password | b64enc }}
  smtp-port: {{ .Values.smtp.port | toString | b64enc }}
  smtp-username: {{ .Values.smtp.username | b64enc }}
  toll-api-key: {{ .Values.thirdparty.toll.key | b64enc }}
  whatsapp-phoneid: {{ .Values.whatsapp.phoneid | toString | b64enc }}
  whatsapp-token: {{ .Values.whatsapp.token | b64enc }}
  whatsapp-webhook: {{ .Values.whatsapp.webhooktoken | b64enc }}
  initialUser: {{ .Values.initialUser | b64enc }}
  platform-fees: {{ .Values.platform.fees | toString | b64enc }}
  platform-gst: {{ .Values.platform.gst | toString | b64enc }}
  acctHolderName: {{ .Values.bankDetails.acctHolderName | b64enc }}
  bankName: {{ .Values.bankDetails.bankName | b64enc }}
  bankAcctNumber: {{ .Values.bankDetails.bankAcctNumber }}
  ifscCode: {{ .Values.bankDetails.ifscCode | b64enc }}
  accountType: {{ .Values.bankDetails.accountType | b64enc }}
  upiID: {{ .Values.bankDetails.upiID | b64enc }}
  companyPAN: {{ .Values.bankDetails.companyPAN | b64enc }}
  companyCIN: {{ .Values.bankDetails.companyCIN | b64enc }}
  company-address: {{ .Values.company.address | b64enc }}
  cgst-rate: {{ .Values.amountDetails.cGstRate | toString | b64enc }}
  sgst-rate: {{ .Values.amountDetails.sGstRate | toString | b64enc }}
  pay-scanner-url: {{ .Values.paymentScanner.url | b64enc }}
  bus-whatsapp-ph-id: {{ .Values.whatsapp.api.whatsappphoneid }}
  bus-whatsapp-token: {{ .Values.whatsapp.api.token | b64enc }}
  bus-whatsapp-webhook-token: {{ .Values.webhook.verify.token | b64enc }}
