apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  postgres-password: {{ .Values.database.postgres.password | b64enc }}
  postgres-username: {{ .Values.database.postgres.username | b64enc }}
  razorpay-api-key-id: {{ .Values.thirdparty.razopay_api.id | b64enc }}
  razorpay-api-key-secret: {{ .Values.thirdparty.razopay_api.secret | b64enc }}
  fast2sms-api-id: {{ .Values.thirdparty.fastsms_api.id | b64enc }} 
  fast2sms-api-url: {{ .Values.thirdparty.fastsms_api.url | b64enc }}
  aws-access-key: {{ .Values.env.aws.access_key | b64enc }}
  aws-secret-key: {{ .Values.env.aws.secret_key | b64enc }}
  aws-bucket-name: {{ .Values.env.aws.bucketName | b64enc }}
  google-map-api-key: {{ .Values.thirdparty.google_maps_api.key | b64enc }}
  google-map-api-url: {{ .Values.thirdparty.google_maps_api.url | b64enc }}
  cipher-secret-key: {{ .Values.cipher.secret.key | b64enc }}
  jwt_secret_key: {{ .Values.application.security.jwt.secret.key | b64enc }}
  jwt-expiration: {{ .Values.application.security.jwt.expiration | b64enc }}
