apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.monitoring.prometheusConfigMap.name }}
  namespace: {{ .Values.monitoring.namespace }}
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      # Scrape Kubernetes API Servers
      - job_name: 'kubernetes-apiservers'
        kubernetes_sd_configs:
        - role: endpoints
        relabel_configs:
        - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
          action: keep
          regex: default;kubernetes;https

      # Scrape Taytelar Application
      - job_name: 'taytelar-application'
        kubernetes_sd_configs:
        - role: endpoints
        relabel_configs:
        - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_label_app, __meta_kubernetes_endpoint_port_name]
          action: keep
          regex: {{ .Values.backend.namespace }};{{ .Values.backend.name }};{{ .Values.backend.metricsPortName }}
        metrics_path: /metrics
        scrape_interval: 15s
