apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.elk.elasticsearch.name }}
  namespace: {{ .Values.elk.namespace }}
spec:
  replicas: {{ .Values.elk.elasticsearch.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.elk.elasticsearch.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.elk.elasticsearch.name }}
    spec:
      containers:
      - name: {{ .Values.elk.elasticsearch.name }}
        image: {{ .Values.elk.elasticsearch.image }}
        resources:
          requests:
            memory: "2Gi"
            cpu: "200m"
          limits:
            memory: "2Gi"
            cpu: "500m"
        env:
        - name: discovery.type
          value: single-node
