apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: {{ .Values.elk.namespace }}
  labels:
    app: {{ .Values.elk.filebeat.name }}
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: log
      enabled: true
      paths:
        - /var/log/pods/taytelar-ns_backend-*/backend/*.log
      fields:
        app: backend
      fields_under_root: true

    output.logstash:
      hosts: ["logstash:5044"]
