apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.elk.filebeat.cluster-role-binding }}
  namespace: {{ .Values.elk.namespace }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.elk.filebeat.name }}
  namespace: default
roleRef:
  kind: ClusterRole
  name: {{ .Values.elk.filebeat.cluster-role }}
  apiGroup: rbac.authorization.k8s.io
