apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: {{ .Values.efk.namespace }}
  labels:
    app: filebeat
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: log
      enabled: true
      paths:
        - /var/log/*.log
      fields:
        app: backend
      fields_under_root: true

    output.logstash: 
      hosts: ["logstash:5044"]  

    setup.kibana:
      host: "kibana:5601"
