apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.monitoring.grafana.name }}
  namespace: {{ .Values.monitoring.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.monitoring.grafana.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.monitoring.grafana.name }}
    spec:
      containers:
        - name: {{ .Values.monitoring.grafana.name }}
          image: {{ .Values.monitoring.grafana.image }}
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.monitoring.grafana.name }}
  namespace: {{ .Values.monitoring.namespace }}
spec:
  selector:
    app: {{ .Values.monitoring.grafana.name }}
  ports:
    - port: {{ .Values.monitoring.grafana.service.port }}
      targetPort: {{ .Values.monitoring.grafana.service.targetPort }}
  type: {{ .Values.monitoring.grafana.service.type }}
