apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: {{ .Values.efk.namespace }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"  # Ensure this is set to false for public access
spec:
  selector:
    app: kibana
  ports:
    - protocol: TCP
      port: 5601
      targetPort: 5601
      nodePort: 30228
  type: LoadBalancer
