apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: {{ .Values.efk.namespace }}
spec:
  selector:
    app: logstash
  ports:
    - protocol: TCP
      port: 5044
      targetPort: 5044
